force-app/main/default/objects/SObjectTypeTestClasse__c/SObjectTypeTestClasse__c.object-meta.xml
<CustomObject>
    <label>SObjectType Test Classe</label>
    <nameField>
        <label>SObjectType Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SObjectTypes Test Classe</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SObjectTypeTestClasse__c/fields/Attribute10__c.field-meta.xml
<CustomField>
    <fullName>Attribute10__c</fullName>
    <label>Attribute10</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SObjectTypeTestClasse__c/fields/Attribute11__c.field-meta.xml
<CustomField>
    <fullName>Attribute11__c</fullName>
    <label>Attribute11</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SObjectTypeTestClasse__c/fields/Attribute12__c.field-meta.xml
<CustomField>
    <fullName>Attribute12__c</fullName>
    <label>Attribute12</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SObjectTypeTestClasse__c/fields/Attribute13__c.field-meta.xml
<CustomField>
    <fullName>Attribute13__c</fullName>
    <label>Attribute13</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SObjectTypeTestClasse__c/fields/Attribute14__c.field-meta.xml
<CustomField>
    <fullName>Attribute14__c</fullName>
    <label>Attribute14</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SObjectTypeTestClasse__c/fields/Attribute15__c.field-meta.xml
<CustomField>
    <fullName>Attribute15__c</fullName>
    <label>Attribute15</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SObjectTypeTestClasse__c/fields/Attribute16__c.field-meta.xml
<CustomField>
    <fullName>Attribute16__c</fullName>
    <label>Attribute16</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SObjectTypeTestClasse__c/fields/Attribute17__c.field-meta.xml
<CustomField>
    <fullName>Attribute17__c</fullName>
    <label>Attribute17</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SObjectTypeTestClasse__c/fields/Attribute18__c.field-meta.xml
<CustomField>
    <fullName>Attribute18__c</fullName>
    <label>Attribute18</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SObjectTypeTestClasse__c/fields/Attribute19__c.field-meta.xml
<CustomField>
    <fullName>Attribute19__c</fullName>
    <label>Attribute19</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SObjectTypeTestClasse__c/fields/Attribute1__c.field-meta.xml
<CustomField>
    <fullName>Attribute1__c</fullName>
    <label>Attribute1</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SObjectTypeTestClasse__c/fields/Attribute20__c.field-meta.xml
<CustomField>
    <fullName>Attribute20__c</fullName>
    <label>Attribute20</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SObjectTypeTestClasse__c/fields/Attribute21__c.field-meta.xml
<CustomField>
    <fullName>Attribute21__c</fullName>
    <label>Attribute21</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SObjectTypeTestClasse__c/fields/Attribute22__c.field-meta.xml
<CustomField>
    <fullName>Attribute22__c</fullName>
    <label>Attribute22</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SObjectTypeTestClasse__c/fields/Attribute23__c.field-meta.xml
<CustomField>
    <fullName>Attribute23__c</fullName>
    <label>Attribute23</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SObjectTypeTestClasse__c/fields/Attribute24__c.field-meta.xml
<CustomField>
    <fullName>Attribute24__c</fullName>
    <label>Attribute24</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SObjectTypeTestClasse__c/fields/Attribute25__c.field-meta.xml
<CustomField>
    <fullName>Attribute25__c</fullName>
    <label>Attribute25</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SObjectTypeTestClasse__c/fields/Attribute26__c.field-meta.xml
<CustomField>
    <fullName>Attribute26__c</fullName>
    <label>Attribute26</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SObjectTypeTestClasse__c/fields/Attribute27__c.field-meta.xml
<CustomField>
    <fullName>Attribute27__c</fullName>
    <label>Attribute27</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SObjectTypeTestClasse__c/fields/Attribute28__c.field-meta.xml
<CustomField>
    <fullName>Attribute28__c</fullName>
    <label>Attribute28</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SObjectTypeTestClasse__c/fields/Attribute29__c.field-meta.xml
<CustomField>
    <fullName>Attribute29__c</fullName>
    <label>Attribute29</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SObjectTypeTestClasse__c/fields/Attribute2__c.field-meta.xml
<CustomField>
    <fullName>Attribute2__c</fullName>
    <label>Attribute2</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SObjectTypeTestClasse__c/fields/Attribute30__c.field-meta.xml
<CustomField>
    <fullName>Attribute30__c</fullName>
    <label>Attribute30</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SObjectTypeTestClasse__c/fields/Attribute31__c.field-meta.xml
<CustomField>
    <fullName>Attribute31__c</fullName>
    <label>Attribute31</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SObjectTypeTestClasse__c/fields/Attribute32__c.field-meta.xml
<CustomField>
    <fullName>Attribute32__c</fullName>
    <label>Attribute32</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SObjectTypeTestClasse__c/fields/Attribute33__c.field-meta.xml
<CustomField>
    <fullName>Attribute33__c</fullName>
    <label>Attribute33</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SObjectTypeTestClasse__c/fields/Attribute34__c.field-meta.xml
<CustomField>
    <fullName>Attribute34__c</fullName>
    <label>Attribute34</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SObjectTypeTestClasse__c/fields/Attribute35__c.field-meta.xml
<CustomField>
    <fullName>Attribute35__c</fullName>
    <label>Attribute35</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SObjectTypeTestClasse__c/fields/Attribute36__c.field-meta.xml
<CustomField>
    <fullName>Attribute36__c</fullName>
    <label>Attribute36</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SObjectTypeTestClasse__c/fields/Attribute37__c.field-meta.xml
<CustomField>
    <fullName>Attribute37__c</fullName>
    <label>Attribute37</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SObjectTypeTestClasse__c/fields/Attribute38__c.field-meta.xml
<CustomField>
    <fullName>Attribute38__c</fullName>
    <label>Attribute38</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SObjectTypeTestClasse__c/fields/Attribute39__c.field-meta.xml
<CustomField>
    <fullName>Attribute39__c</fullName>
    <label>Attribute39</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SObjectTypeTestClasse__c/fields/Attribute3__c.field-meta.xml
<CustomField>
    <fullName>Attribute3__c</fullName>
    <label>Attribute3</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SObjectTypeTestClasse__c/fields/Attribute40__c.field-meta.xml
<CustomField>
    <fullName>Attribute40__c</fullName>
    <label>Attribute40</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SObjectTypeTestClasse__c/fields/Attribute4__c.field-meta.xml
<CustomField>
    <fullName>Attribute4__c</fullName>
    <label>Attribute4</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SObjectTypeTestClasse__c/fields/Attribute5__c.field-meta.xml
<CustomField>
    <fullName>Attribute5__c</fullName>
    <label>Attribute5</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SObjectTypeTestClasse__c/fields/Attribute6__c.field-meta.xml
<CustomField>
    <fullName>Attribute6__c</fullName>
    <label>Attribute6</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SObjectTypeTestClasse__c/fields/Attribute7__c.field-meta.xml
<CustomField>
    <fullName>Attribute7__c</fullName>
    <label>Attribute7</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SObjectTypeTestClasse__c/fields/Attribute8__c.field-meta.xml
<CustomField>
    <fullName>Attribute8__c</fullName>
    <label>Attribute8</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SObjectTypeTestClasse__c/fields/Attribute9__c.field-meta.xml
<CustomField>
    <fullName>Attribute9__c</fullName>
    <label>Attribute9</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SObjectTypeTestClasse__c/fields/LineOrder__c.field-meta.xml
<CustomField>
    <fullName>LineOrder__c</fullName>
    <label>LineOrder</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SObjectTypeTestClasse__c/fields/lineType__c.field-meta.xml
<CustomField>
    <fullName>lineType__c</fullName>
    <label>lineType</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>header</fullName>
            </value>
            <value>
                <fullName>line</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SObjectTypeTestClasse__c/fields/SObjectType__c.field-meta.xml
<CustomField>
    <fullName>SObjectType__c</fullName>
    <label>SObjectType</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Account</fullName>
            </value>
            <value>
                <fullName>Contract</fullName>
            </value>
            <value>
                <fullName>Contact</fullName>
            </value>
            <value>
                <fullName>Opportunity</fullName>
            </value>
            <value>
                <fullName>Product2</fullName>
            </value>
            <value>
                <fullName>User</fullName>
            </value>
            <value>
                <fullName>Case</fullName>
            </value>
            <value>
                <fullName>TimeSheet__c</fullName>
            </value>
            <value>
                <fullName>periode__c</fullName>
            </value>
            <value>
                <fullName>TimeSheetEntry__c</fullName>
            </value>
            <value>
                <fullName>Invoice__c</fullName>
            </value>
            <value>
                <fullName>InvoiceLine__c</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/SObjectTypeTestClasseController.cls
/**
 * Controller for the SObjectTypeTestClasse LWC
 */
public with sharing class SObjectTypeTestClasseController {
    
    /**
     * Gets all SObjectTypeTestClasse__c records with all attributes
     * @return List of SObjectTypeTestClasse__c records
     */
    @AuraEnabled(cacheable=true)
    public static List<SObjectTypeTestClasse__c> getSObjectTypeTestClasses() {
        
            return [SELECT 
                    Id,
                    SObjectType__c,
                    Name, 
                    lineType__c,
                    LineOrder__c, 
                    Attribute1__c, 
                    Attribute2__c, 
                    Attribute3__c, 
                    Attribute4__c, 
                    Attribute5__c, 
                    Attribute6__c, 
                    Attribute7__c, 
                    Attribute8__c, 
                    Attribute9__c,
                    Attribute10__c, 
                    Attribute11__c, 
                    Attribute12__c, 
                    Attribute13__c, 
                    Attribute14__c, 
                    Attribute15__c, 
                    Attribute16__c, 
                    Attribute17__c, 
                    Attribute18__c, 
                    Attribute19__c,
                    Attribute20__c, 
                    Attribute21__c, 
                    Attribute22__c, 
                    Attribute23__c, 
                    Attribute24__c, 
                    Attribute25__c, 
                    Attribute26__c, 
                    Attribute27__c, 
                    Attribute28__c, 
                    Attribute29__c,
                    Attribute30__c, 
                    Attribute31__c, 
                    Attribute32__c, 
                    Attribute33__c, 
                    Attribute34__c, 
                    Attribute35__c, 
                    Attribute36__c, 
                    Attribute37__c, 
                    Attribute38__c, 
                    Attribute39__c,
                    Attribute40__c,
                    CreatedById, 
                    CreatedDate
                FROM SObjectTypeTestClasse__c
                WITH SECURITY_ENFORCED
                ORDER BY Name ASC
            ];
       
    }
    
    /**
     * Gets a specific SObjectTypeTestClasse__c record by Id
     * @param recordId The Id of the SObjectTypeTestClasse__c record
     * @return SObjectTypeTestClasse__c record
     */
    @AuraEnabled(cacheable=true)
    public static SObjectTypeTestClasse__c getSObjectTypeTestClasseById(Id recordId) {
        try {
            return [SELECT 
                    Id,
                    SObjectType__c,
                    Name, 
                    lineType__c,
                    LineOrder__c, 
                    Attribute1__c, 
                    Attribute2__c, 
                    Attribute3__c, 
                    Attribute4__c, 
                    Attribute5__c, 
                    Attribute6__c, 
                    Attribute7__c, 
                    Attribute8__c, 
                    Attribute9__c,
                    Attribute10__c, 
                    Attribute11__c, 
                    Attribute12__c, 
                    Attribute13__c, 
                    Attribute14__c, 
                    Attribute15__c, 
                    Attribute16__c, 
                    Attribute17__c, 
                    Attribute18__c, 
                    Attribute19__c,
                    Attribute20__c, 
                    Attribute21__c, 
                    Attribute22__c, 
                    Attribute23__c, 
                    Attribute24__c, 
                    Attribute25__c, 
                    Attribute26__c, 
                    Attribute27__c, 
                    Attribute28__c, 
                    Attribute29__c,
                    Attribute30__c, 
                    Attribute31__c, 
                    Attribute32__c, 
                    Attribute33__c, 
                    Attribute34__c, 
                    Attribute35__c, 
                    Attribute36__c, 
                    Attribute37__c, 
                    Attribute38__c, 
                    Attribute39__c,
                    Attribute40__c,
                    CreatedById, 
                    CreatedDate
                FROM SObjectTypeTestClasse__c
                WHERE Id = :recordId
                WITH SECURITY_ENFORCED
                LIMIT 1
            ];
        } catch (Exception e) {
            throw new AuraHandledException('Error retrieving SObjectTypeTestClasse record: ' + e.getMessage());
        }
    }
     @AuraEnabled(cacheable=true)
    public static List<String> getTableHeaders() {
        List<String> headers = new List<String>();
        List<FieldDefinition> listAttribute = [SELECT id, DeveloperName, QualifiedApiName FROM FieldDefinition WHERE EntityDefinition.DeveloperName = 'SObjectTypeTestClasse'];
        for(FieldDefinition field : listAttribute){
            if (field.QualifiedApiName.contains('Attribute'))  headers.add(field.QualifiedApiName);
        }
        return headers;
    }
    @AuraEnabled(cacheable=true)
    public static Map<String, SObjectTypeTestClasse__c> getHeaderRecords() {
        
            Map<String, SObjectTypeTestClasse__c> headerMap = new Map<String, SObjectTypeTestClasse__c>();
            
            List<SObjectTypeTestClasse__c> headerRecords = [
                SELECT 
                    Id, SObjectType__c, Name, lineType__c,
                    Attribute1__c, Attribute2__c, Attribute3__c, Attribute4__c, 
                    Attribute5__c, Attribute6__c, Attribute7__c, Attribute8__c, 
                    Attribute9__c, Attribute10__c, Attribute11__c, Attribute12__c, 
                    Attribute13__c, Attribute14__c, Attribute15__c, Attribute16__c, 
                    Attribute17__c, Attribute18__c, Attribute19__c, Attribute20__c,
                    Attribute21__c, Attribute22__c, Attribute23__c, Attribute24__c, 
                    Attribute25__c, Attribute26__c, Attribute27__c, Attribute28__c, 
                    Attribute29__c, Attribute30__c, Attribute31__c, Attribute32__c,
                    Attribute33__c, Attribute34__c, Attribute35__c, Attribute36__c, 
                    Attribute37__c, Attribute38__c, Attribute39__c, Attribute40__c
                FROM SObjectTypeTestClasse__c
                WHERE lineType__c = 'header'
                WITH SECURITY_ENFORCED
            ];
            
            for (SObjectTypeTestClasse__c header : headerRecords) {
                headerMap.put(header.SObjectType__c, header);
            }
            
            return headerMap;
       
    }  
    
    /**
     * Gets data for CSV export with a subset of fields
     * @return List of SObjectTypeTestClasse__c records with selected fields for export
     */
    @AuraEnabled(cacheable=true)
    public static List<SObjectTypeTestClasse__c> getDataForExport() {
      
            return [SELECT 
                    Name,
                    SObjectType__c,
                    lineType__c,
                    LineOrder__c,
                    Attribute1__c,
                    Attribute2__c,
                    Attribute3__c,
                    Attribute4__c,
                    Attribute5__c,
                    Attribute6__c,
                    Attribute7__c,
                    Attribute8__c,
                    Attribute9__c,
                    Attribute10__c,
                    Attribute11__c,
                    Attribute12__c,
                    Attribute13__c,
                    Attribute14__c,
                    Attribute15__c,
                    Attribute16__c,
                    Attribute17__c,
                    Attribute18__c
                FROM SObjectTypeTestClasse__c
                WITH SECURITY_ENFORCED
                ORDER BY Name ASC
            ];
        
    }
}